CREATE TABLE IMAGES IF NOT EXISTS;
-- Drop TABLE images;

CREATE TABLE IMAGES(
    ID INTEGER PRIMARY KEY,
    FILE_NAME TEXT NOT NULL,
    IMAGE_URL TEXT NOT NULL,
    WIDTH INTEGER NOT NULL,
    HEIGHT INTEGER NOT NULL,
    FORMAT TEXT NOT NULL,
    AVG_COLOUR FLOAT NOT NULL,
    FETCHED_AT TEXT NOT NULL
);